/*
 * File:           AsiddurTefillaAnnotatedHandlerImpl.java
 * Date:           November 20, 2006  11:02 PM
 *
 * @author  shmuelp
 * @version generated by NetBeans XML module
 */
package tefillaconverter;
import org.xml.sax.*;
public class AsiddurTefillaAnnotatedHandlerImpl implements AsiddurTefillaAnnotatedHandler {

   public static final boolean DEBUG = false;

   public void start_asiddur_annotated(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("start_asiddur_annotated: " + meta);
   }

   public void end_asiddur_annotated() throws SAXException {
      if (DEBUG) System.err.println("end_asiddur_annotated()");
   }

   public void handle_text_header(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("handle_text_header: " + meta);
   }

   public void handle_get(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("handle_get: " + meta);
   }

   public void start_toc(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("start_toc: " + meta);
   }

   public void end_toc() throws SAXException {
      if (DEBUG) System.err.println("end_toc()");
   }

   public void handle_include(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("handle_include: " + meta);
   }

   public void handle_p(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("handle_p: " + meta);
   }

   public void handle_function(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("handle_function: " + meta);
   }

   public void start_tefillot(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("start_tefillot: " + meta);
   }

   public void end_tefillot() throws SAXException {
      if (DEBUG) System.err.println("end_tefillot()");
   }

   public void start_text(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("start_text: " + meta);
   }

   public void handle_text(final java.lang.String data, final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("handle_text: " + data);
   }

   public void end_text() throws SAXException {
      if (DEBUG) System.err.println("end_text()");
   }

   public void handle_set(final java.lang.String data, final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("handle_set: " + data);
   }

   public void handle_else(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("handle_else: " + meta);
   }

   public void handle_br(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("handle_br: " + meta);
   }

   public void start_if(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("start_if: " + meta);
   }

   public void handle_if(final java.lang.String data, final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("handle_if: " + data);
   }

   public void end_if() throws SAXException {
      if (DEBUG) System.err.println("end_if()");
   }

   public void handle_navmark(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("handle_navmark: " + meta);
   }

   public void start_texts(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("start_texts: " + meta);
   }

   public void end_texts() throws SAXException {
      if (DEBUG) System.err.println("end_texts()");
   }

   public void handle_name(final java.lang.String data, final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("handle_name: " + data);
   }

   public void start_tefilla(final Attributes meta) throws SAXException {
      if (DEBUG) System.err.println("start_tefilla: " + meta);
   }

   public void end_tefilla() throws SAXException {
      if (DEBUG) System.err.println("end_tefilla()");
   }
}
