/*
 * File:           AsiddurTefillaAnnotatedHandler.java
 * Date:           November 20, 2006  11:02 PM
 *
 * @author  shmuelp
 * @version generated by NetBeans XML module
 */
package tefillaconverter;
import org.xml.sax.*;
public interface AsiddurTefillaAnnotatedHandler {

   /**
    * 
    * A container element start event handling method.
    * @param meta attributes
    */
   public void start_asiddur_annotated(final Attributes meta) throws SAXException;

   /**
    * 
    * A container element end event handling method.
    */
   public void end_asiddur_annotated() throws SAXException;

   /**
    * 
    * An empty element event handling method.
    * @param data value or null
    */
   public void handle_text_header(final Attributes meta) throws SAXException;

   /**
    * 
    * An empty element event handling method.
    * @param data value or null
    */
   public void handle_get(final Attributes meta) throws SAXException;

   /**
    * 
    * A container element start event handling method.
    * @param meta attributes
    */
   public void start_toc(final Attributes meta) throws SAXException;

   /**
    * 
    * A container element end event handling method.
    */
   public void end_toc() throws SAXException;

   /**
    * 
    * An empty element event handling method.
    * @param data value or null
    */
   public void handle_include(final Attributes meta) throws SAXException;

   /**
    * 
    * An empty element event handling method.
    * @param data value or null
    */
   public void handle_p(final Attributes meta) throws SAXException;

   /**
    * 
    * An empty element event handling method.
    * @param data value or null
    */
   public void handle_function(final Attributes meta) throws SAXException;

   /**
    * 
    * A container element start event handling method.
    * @param meta attributes
    */
   public void start_tefillot(final Attributes meta) throws SAXException;

   /**
    * 
    * A container element end event handling method.
    */
   public void end_tefillot() throws SAXException;

   /**
    * 
    * A container element start event handling method.
    * @param meta attributes
    */
   public void start_text(final Attributes meta) throws SAXException;

   /**
    * 
    * A data element event handling method.
    * @param data value or null 
    * @param meta attributes
    */
   public void handle_text(final java.lang.String data, final Attributes meta) throws SAXException;

   /**
    * 
    * A container element end event handling method.
    */
   public void end_text() throws SAXException;

   /**
    * 
    * A data element event handling method.
    * @param data value or null 
    * @param meta attributes
    */
   public void handle_set(final java.lang.String data, final Attributes meta) throws SAXException;

   /**
    * 
    * An empty element event handling method.
    * @param data value or null
    */
   public void handle_else(final Attributes meta) throws SAXException;

   /**
    * 
    * An empty element event handling method.
    * @param data value or null
    */
   public void handle_br(final Attributes meta) throws SAXException;

   /**
    * 
    * A container element start event handling method.
    * @param meta attributes
    */
   public void start_if(final Attributes meta) throws SAXException;

   /**
    * 
    * A data element event handling method.
    * @param data value or null 
    * @param meta attributes
    */
   public void handle_if(final java.lang.String data, final Attributes meta) throws SAXException;

   /**
    * 
    * A container element end event handling method.
    */
   public void end_if() throws SAXException;

   /**
    * 
    * An empty element event handling method.
    * @param data value or null
    */
   public void handle_navmark(final Attributes meta) throws SAXException;

   /**
    * 
    * A container element start event handling method.
    * @param meta attributes
    */
   public void start_texts(final Attributes meta) throws SAXException;

   /**
    * 
    * A container element end event handling method.
    */
   public void end_texts() throws SAXException;

   /**
    * 
    * A data element event handling method.
    * @param data value or null 
    * @param meta attributes
    */
   public void handle_name(final java.lang.String data, final Attributes meta) throws SAXException;

   /**
    * 
    * A container element start event handling method.
    * @param meta attributes
    */
   public void start_tefilla(final Attributes meta) throws SAXException;

   /**
    * 
    * A container element end event handling method.
    */
   public void end_tefilla() throws SAXException;
}
